apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: dgraph-alpha-deployment
  annotations:
    description: "Dgraph Alpha"
    openshift.io/display-name: 'Dgraph Alpha'
    version: 0.2.0
    tags: dgraph,alpha,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: "This is an OpenShift Template to deploy Dgraph Alphas"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: dgraph-alpha-deployment
    app: dgraph
    component: alpha

parameters:
  - description: "Hostname to be used for exposing the REST API"
    displayName: "REST Hostname"
    required: true
    name: HOST_NAME_REST
    value: "alpha-rest-thoth-dgraph-stage.cloud.paas.psi.redhat.com"

  - description: "Hostname to be used for exposing the gRPC API"
    displayName: "gRPC Hostname"
    required: true
    name: HOST_NAME_GRPC
    value: "alpha-grpc-thoth-dgraph-stage.cloud.paas.psi.redhat.com"

  - description: "StorageClass to be used"
    displayName: "StorageClass"
    required: true
    name: STORAGE_CLASS_NAME
    value: "ceph-dyn-thoth-paas-prod-psi"

  - description: "Storage size to be used (dont forget the Gi)"
    displayName: "Storage size"
    required: true
    name: STORAGE_SIZE
    value: "5Gi"

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: alpha-public
      labels:
        app: dgraph
        component: alpha
    spec:
      type: LoadBalancer
      ports:
        - port: 8080
          targetPort: 8080
          name: alpha-rest
        - port: 9080
          targetPort: 9080
          name: alpha-grpc
      selector:
        app: dgraph
        component: alpha

  # This is a headless service which is necessary for discovery for a dgraph-alpha StatefulSet.
  # https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#creating-a-statefulset
  - apiVersion: v1
    kind: Service
    metadata:
      name: alpha
      labels:
        app: dgraph
        component: alpha
    spec:
      ports:
      - port: 7080
        targetPort: 7080
        name: alpha-grpc-int
      clusterIP: None
      selector:
        app: dgraph
        component: alpha

  # This StatefulSet runs 3 replicas of Dgraph Alpha.
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: alpha
      labels:
        app: dgraph
        component: alpha
    spec:
      serviceName: alpha
      replicas: 3
      selector:
        matchLabels:
          app: dgraph
          component: alpha
      template:
        metadata:
          labels:
            app: dgraph
            component: alpha
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - alpha
                    topologyKey: kubernetes.io/hostname
          # Initializing the Alphas:
          #
          # You may want to initialize the Alphas with data before starting, e.g.
          # with data from the Dgraph Bulk Loader: https://docs.dgraph.io/deploy/#bulk-loader.
          # You can accomplish by uncommenting this initContainers config. This
          # starts a container with the same /dgraph volume used by Alpha and runs
          # before Alpha starts.
          #
          # You can copy your local p directory to the pod's /dgraph/p directory
          # with this command:
          #
          #    kubectl cp path/to/p dgraph-alpha-0:/dgraph/ -c init-alpha
          #    (repeat for each alpha pod)
          #
          # When you're finished initializing each Alpha data directory, you can signal
          # it to terminate successfully by creating a /dgraph/doneinit file:
          #
          #    kubectl exec dgraph-alpha-0 -c init-alpha touch /dgraph/doneinit
          #
          # Note that pod restarts cause re-execution of Init Containers. Since
          # /dgraph is persisted across pod restarts, the Init Container will exit
          # automatically when /dgraph/doneinit is present and proceed with starting
          # the Alpha process.
          #
          # Tip: StatefulSet pods can start in parallel by configuring
          # .spec.podManagementPolicy to Parallel:
          #
          #     https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees
          #
          # initContainers:
          #   - name: init-alpha
          #     image: dgraph/dgraph:latest
          #     command:
          #       - bash
          #       - "-c"
          #       - |
          #         echo "Write to /dgraph/doneinit when ready."
          #         until [ -f /dgraph/doneinit ]; do sleep 2; done
          #     volumeMounts:
          #       - name: datadir
          #         mountPath: /dgraph
          containers:
            - name: alpha
              image: dgraph
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 7080
                  name: alpha-grpc-int
                - containerPort: 8080
                  name: alpha-rest
                - containerPort: 9080
                  name: alpha-grpc
              volumeMounts:
                - name: datadir
                  mountPath: /dgraph
                - name: dgraph-tls
                  mountPath: /var/run/secrets/dgraph
                  readOnly: true
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: ADMIN_WHITELIST_IPS
                  value: "172.54.0.0:172.54.255.255"
              command:
                - bash
                - "-c"
                - |
                  set -ex
                  dgraph alpha --my=$(hostname -f):7080 --lru_mb 7680 --zero zero-0.zero.${POD_NAMESPACE}.svc.cluster.local:5080 --tls_dir /var/run/secrets/dgraph --whitelist ${ADMIN_WHITELIST_IPS}
              resources:
                limits:
                  cpu: 4
                  memory: 8Gi
                requests:
                  cpu: 4
                  memory: 8Gi
          terminationGracePeriodSeconds: 60
          volumes:
            - name: datadir
              persistentVolumeClaim:
                claimName: datadir
            - name: dgraph-tls
              secret:
                defaultMode: 420
                secretName: dgraph-tls
      updateStrategy:
        type: RollingUpdate
      volumeClaimTemplates:
        - metadata:
            name: "datadir"
            finalizers:
              - "kubernetes.io/pvc-protection"
          spec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: "${STORAGE_SIZE}"
            storageClassName: "${STORAGE_CLASS_NAME}"

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: dgraph
        component: alpha
      name: alpha-rest
    spec:
      host: "${HOST_NAME_REST}"
      port:
        targetPort: alpha-rest
      tls:
        termination: passthrough
      to:
        kind: Service
        name: alpha-public
        weight: 100
      wildcardPolicy: None

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: dgraph
        component: alpha
      name: alpha-grpc
    spec:
      host: "${HOST_NAME_GRPC}"
      port:
        targetPort: alpha-grpc
      tls:
        termination: passthrough
      to:
        kind: Service
        name: alpha-public
        weight: 100
      wildcardPolicy: None