kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dgraph
spec:
  lookupPolicy:
    local: true
  tags:
  - name: v1.0.13
    from:
      kind: DockerImage
      name: docker.io/dgraph/dgraph:v1.0.13
    referencePolicy:
      type: Local
  - name: v1.0.14
    from:
      kind: DockerImage
      name: docker.io/dgraph/dgraph:v1.0.14
    referencePolicy:
      type: Local
  - name: v1.0.15-rc1
    from:
      kind: DockerImage
      name: docker.io/dgraph/dgraph:v1.0.15-rc1
    referencePolicy:
      type: Local
