---
apiVersion: v1
kind: Service
metadata:
  name: ratel-public
  labels:
    app: dgraph
    component: ratel
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    name: ratel-http
  selector:
    app: dgraph
    component: ratel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratel
  labels:
    app: dgraph
    component: ratel
spec:
  selector:
    matchLabels:
      app: dgraph
      component: ratel
  template:
    metadata:
      labels:
        app: dgraph
        component: ratel
    spec:
      containers:
      - name: ratel
        image: dgraph
        ports:
        - containerPort: 8000
        command:
          - dgraph-ratel